version: 2.1
jobs:
  Unit Test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test
  Visual Test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: |
          curl -sSL https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install -y git-lfs
      - checkout
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh git@github.com git-lfs-authenticate "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" download
          git lfs pull
      - run: |
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: |
          nvm install 12
          nvm use 12
          npm install
          npm run test:visual
  Build and Publish Image:
    parameters:
      tag:
        type: string
        default: latest
      should-tag-latest:
        type: boolean
        default: false

    docker:
      - image: docker:latest

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: echo "${DOCKER_SERVICE_KEY}" | docker login -u _json_key --password-stdin https://gcr.io
      - run: docker build -t gcr.io/rxjs-fiddle/frontend:<< parameters.tag >> -f Dockerfile .
      - run: docker push gcr.io/rxjs-fiddle/frontend

  Bump Git Tag:
    docker:
      - image: gcr.io/rxjs-fiddle/ci/gitversion:0.0.8
        auth:
          username: _json_key
          password: ${DOCKER_SERVICE_KEY}

    steps:
      - add_ssh_keys:
          fingerprints:
            - 'f9:48:ae:4c:7a:46:c9:f1:b4:8d:a3:4a:5c:03:37:9a'
      - checkout
      - run: gitversion bump auto
      - run: git push origin --tags

workflows:
  Tag Latest Image for Commits to Master:
    jobs:
      - Unit Test
      - Visual Test
      - Build and Publish Image:
          requires:
            - Unit Test
            - Visual Test
          tag: latest
          filters:
            branches:
              only: master
      - Hold for Publish To Production:
          type: approval
          requires:
            - Build and Publish Image
          filters:
            branches:
              only: master
      - Bump Git Tag:
          requires:
            - Hold for Publish To Production
          filters:
            branches:
              only: master

  Tag Semver Image for Tags:
    jobs:
      - Build and Publish Image:
          tag: ${CIRCLE_TAG}
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
